# Generated by Django 5.2.7 on 2025-12-03 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_authorityprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='user',
        ),
        migrations.DeleteModel(
            name='AuthorityProfile',
        ),
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
