# Generated by Django 5.2.8 on 2025-12-03 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_authorityprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorityprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='authority_logos/'),
        ),
        migrations.AlterField(
            model_name='authorityprofile',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='authorityprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='authorityprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
